# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: "Build & test"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
      # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
      #
      #      ┌───────────── minute (0 - 59)
      #      │ ┌───────────── hour (0 - 23)
      #      │ │ ┌───────────── day of the month (1 - 31)
      #      │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
      #      │ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
      #      │ │ │ │ │
    - cron: '1 2 3 * *'  # run at 2:01 every month on the 3rd day

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        bazel: [ '6.0.0' ]
        os: [ 'ubuntu-24.04', 'ubuntu-22.04', 'macos-13', 'macos-12' ]
    env:
      USE_BAZEL_VERSION: '${{ matrix.bazel }}'

    name: Running on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - uses: bazel-contrib/setup-bazel@0.8.1
        with:
          # Avoid downloading Bazel every time.
          bazelisk-cache: true
          # Store build cache per workflow.
          disk-cache: ${{ github.workflow }}
          # Share repository cache between workflows.
          repository-cache: true

      - name: Build
        run: bazel build --config=ci //...
